interactive: enable
qap: disable
websockets.qap.oc: enable
websockets.qap: enable
websockets.port: 8012
keep.alive: enable
oob.idle.interval: 1
oob: enable
console.oob: enable
forward.stdio: enable
console.input: enable
interactive: enable
source: /Users/deepayan/git/github-packages/jsrepl/inst/setup.R
daemon: disable
